name: Release
on:
  push:
    tags:
      - v*
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/release.yml'
      - '.goreleaser.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  release:
    name: Release on Github
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1

      -
        name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=tag_name::${GITHUB_REF#refs/tags/}
          fi

      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      -
        name: tidy
        run: go mod tidy

      -
        name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      -
        name: GitHub Release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
